# Generated by Django 2.0.4 on 2018-04-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20180428_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='num_rooms',
            field=models.IntegerField(default=100),
        ),
    ]
