# Generated by Django 2.0.4 on 2018-05-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_hotel_num_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
