# Generated by Django 2.0.4 on 2018-05-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer',
            new_name='client_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_email',
            field=models.EmailField(default='Smith', max_length=254),
            preserve_default=False,
        ),
    ]
