# Generated by Django 2.0.4 on 2018-05-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180430_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_start',
        ),
        migrations.AddField(
            model_name='reservation',
            name='res_date',
            field=models.DateField(default='2020-01-01', verbose_name='Date of the stay.'),
            preserve_default=False,
        ),
    ]
