# Generated by Django 2.0.4 on 2018-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180430_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='res_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default='1900-01-01', verbose_name='End of the stay.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default='1900-01-01', verbose_name='Start of the stay.'),
            preserve_default=False,
        ),
    ]
